// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wetbeowfxkmszpltjmqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndldGJlb3dmeGttc3pwbHRqbXF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjAyNDMsImV4cCI6MjA3NDEzNjI0M30.d-Du4BqK46jqTSlw8ZkuSbf8Qxr4FiInp4i-0y4r3d0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);